import os
# Force the underlying LangChain-Anthropic client to stop wrapping trailing messages as prefill
os.environ["LANGCHAIN_ANTHROPIC_DISABLE_PREFILL"] = "true"

# --- AGGRESSIVE MONKEY-PATCH CODESECTION ---
# Intercept the underlying language model's invoke/generate method
# Get the true underlying LLM object bypassing the Pydantic wrapper
# Depending on the LangChain wrapper version, it's either agent.llm.bound or agent.llm
from langchain_anthropic import ChatAnthropic
from langchain_core.messages import AIMessage, HumanMessage

original_generate = ChatAnthropic._generate

# Save a reference to the real generator method
original_generate = ChatAnthropic._generate


def patched_generate(self, messages, *args, **kwargs):
    if isinstance(messages, list) and len(messages) > 0:
        # Forcefully strip ANY message that causes a trailing assistant state
        # directly modifying a copy so we don't break the original LangGraph state
        messages = list(messages)

        while messages and isinstance(messages[-1], AIMessage):
            messages.pop()

        # Optional Safeguard: If it still leaves the state dangling or empty,
        # ensure it finishes cleanly with a tiny human acknowledgment.
        if len(messages) == 0:
            messages.append(HumanMessage(content="Please proceed."))

    return original_generate(self, messages, *args, **kwargs)


ChatAnthropic._generate = patched_generate
# -------------------------------------------------
# Overwrite the class level method so every instance gets the fix
ChatAnthropic._generate = patched_generate

# ---------------------------------
# Set up your LLM API Key (Biomni natively leverages models like Claude)
#os.environ["ANTHROPIC_API_KEY"] = "your-api-key-here"
os.environ["ANTHROPIC_API_KEY"] = "<insert your key here>"

# Now safely import the Biomnni agent
from biomni.config import default_config
from biomni.agent import A1
# Set defaults for running Biomni
default_config.max_iterations = 2
default_config.timeout_seconds = 60  # Kill execution if it hangs too lo
default_config.temperature = 0.1

# 1. Initialize the Biomni A1 agent using Claude Sonnet 4.6
# Specify the data cache directory and the foundational reasoning LLM
agent = A1(path='./data', llm='claude-sonnet-4-6')
#agent = A1(path='./data', llm='claude-3-5-sonnet-20241022')

# 2. Attach your custom MCP configuration file for tool enhancement
agent.add_mcp(config_path="./mcp_config.yaml")

# 3. Define your single-cell bioinformatics tasks as a single cohesive prompt
sc_rna_task = (
    "Analyze this single-cell RNA-seq dataset located at ./data/pbmc_sample.h5ad:\n"
    "1. Run quality control (QC) filtering out low-quality cells (high mitochondrial ratio or low counts).\n"
    "2. Perform normalization, log-transformation, and find highly variable genes.\n"
    "3. Compute PCA and cluster the cell populations using a UMAP embedding.\n"
    "4. Annotate the cell clusters using canonical marker genes.\n"
    "5. Identify differentially expressed genes (DEGs) between the Control and Treated conditions."
)

# 4. Pass the string into the agent execution loop
print("Starting single-cell RNA-seq analysis via Biomni LLM...")
result = agent.go(sc_rna_task)

# 5. Output the textual insights and interpretation generated by the agent
print("\n--- Analysis Report Summary ---")
print(result)

# 6. Save the full execution history and generated plots/code to a PDF report
agent.save_conversation_history("scrna_seq_analysis_report.pdf")
print("Analysis complete. Detailed report saved to scrna_seq_analysis_report.pdf")
print()
